### ISSUE TITLE
A few typos

### ISSUE THREAD

**Issue by Clownacy** [SKingBlue/Sonic-Adventure-Retranslated#1]
I was just playing through the game, making mental notes of if I saw anything odd, but a few times I'd see something I thought was a typo, but the text would disappear before I had a chance to double-check. Anyhow, there are three things I noticed so far (I stopped playing after noticing the last one to post about it here). They're all in Sonic's story.

The first one I think I saw was during the cutscene in the Mystic Ruins, after Egg Hornet. The line `If we don't let him get the Emeralds, \nChaos shouldn't transform any further!` - I could have sworn the word 'Chaos' didn't appear. I recall staring at the sentence for a few seconds, trying to make sense of it.

The next was in the cutscene after the Chaos 4 fight. The final line, `Alright...\nLet's go Tails!`; I could have sworn Tails was talking when that subtitle popped up, so it should say 'Sonic', right?

The last one, I know for sure I saw. After fighting Gamma, Tails says `This ship is loosing altitude`, when it should be 'losing' instead.

EDIT: Two more:

Right before the Chaos 6 fight, Sonic says `Is that frog your freind?`. 'friend' is misspelt.

Before Final Egg, Sonic says `How dare you show your  face!`. There are two spaces between 'your' and 'face'.

EDIT: More, this time from Tails's story.

After being rescued by Sonic at the start of the game, Sonic says `I'm just glad I happened \nto se you up there.`. 'see' is misspelt.

Also, `Hehe, this time I'm thinking of \nsomething even more amazing!` displays for barely a second, before displaying a completely blank line for the rest of that line of dialogue.

After the Egg Hornet fight, Eggman says `I'll use him  to destroy \nStation Square...!`. There are two spaces between 'him' and 'to'.

```
The next was in the cutscene after the Chaos 4 fight. The final line, `Alright...\nLet's go Tails!`; I could have sworn Tails was talking when that subtitle popped up, so it should say 'Sonic', right?
```

I saw this in Tails' story, too.

During the Tikal flashback after Sand Hill, Tikal says `And that I musn't ever  forget it.   \n...It goes like this.`. There are two spaces between 'ever' and 'forget'.

Just before Sky Chase Act 2, Tails says `In theory,\n there shouldn't be any problems...`, there's a space after the newline, making the line look odd.

After Tails fights Gamma, Sonic says `I'll folow Eggman! \nI can't afford to ignore him!`. 'follow' is misspelt.

**Comment by SKingBlue** [comment]
Any others? I plan on making one big update that fixes everything

**Comment by Clownacy** [comment]
Sorry, I still haven't finished my playthrough.

**Comment by SKingBlue** [comment]
That's fine just let me know if you find anything
